io.write("W: ")
local W = io.read("*n")
io.write("Q: ")
local Q = io.read("*n")
local QtoStr = tostring(Q)
local q = tonumber(string.sub(QtoStr, 1, 1))
local w = tonumber(string.sub(QtoStr, 2, 2))
local e = tonumber(string.sub(QtoStr, 3, 3))

print(W * e)
print(W * w)
print(W * q)
print(W * Q)
